### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by assertchris**
Number of changes here:

- Usage message has been moved into an include.
- PSR-2 formatting.
- Whitespace/quote [consistency] formatting.
- Added a few PHPDoc things.
- Added a few new binaries to `.gitignore`.

Hopefully all that is to your liking. Happy to change what you don't like. Unless you don't like any of it. I have no idea what will happen then. Probably tears. Big tears of sadness.

### CODE REVIEW

**Comment by evert** [comment]
Looks good! Only thing I'd want to change is the 'usage include'. If it appears in the `bin/` directory, it should imply for me that it needs to be executable.

So either merge it back into the main script, or add it to `src/` if you can =) Otherwise :+1:

**Comment by assertchris** [comment]
Ah, good point...

**Comment by assertchris** [comment]
Sorted!

**Comment by evert** [comment]
Brilliant, thanks!

**Comment by assertchris** [comment]
You're welcome.

**Pull request merged**
